// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeAcom.epp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYeXRYGZrMdRVtMIKtV1-Xn4TA-Or5YI',
    appId: '1:19202381610:web:6c8c452cff8d89fb393053',
    messagingSenderId: '19202381610',
    projectId: 'tastefinder1',
    authDomain: 'tastefinder1.firebaseapp.com',
    storageBucket: 'tastefinder1.appspot.com',
    measurementId: 'G-TGFGG4K9ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQjYaLC-rgdDnUZ9Fr6hhF4Q8yL4bY5w',
    appId: '1:19202381610:android:86567310c62ca63d393053',
    messagingSenderId: '19202381610',
    projectId: 'tastefinder1',
    storageBucket: 'tastefinder1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb6HNADUdH_0pVOzCrbYjVvjUTUCLrOKM',
    appId: '1:19202381610:ios:f8f54e9bc768f3e6393053',
    messagingSenderId: '19202381610',
    projectId: 'tastefinder1',
    storageBucket: 'tastefinder1.appspot.com',
    androidClientId: '19202381610-ppt8vqpmfutisru664c7llvv7564ll5k.apps.googleusercontent.com',
    iosClientId: '19202381610-ngmp7k7h9r8jcbslvph27lfukak2955q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasteFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb6HNADUdH_0pVOzCrbYjVvjUTUCLrOKM',
    appId: '1:19202381610:ios:f8f54e9bc768f3e6393053',
    messagingSenderId: '19202381610',
    projectId: 'tastefinder1',
    storageBucket: 'tastefinder1.appspot.com',
    androidClientId: '19202381610-ppt8vqpmfutisru664c7llvv7564ll5k.apps.googleusercontent.com',
    iosClientId: '19202381610-ngmp7k7h9r8jcbslvph27lfukak2955q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasteFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhYeXRYGZrMdRVtMIKtV1-Xn4TA-Or5YI',
    appId: '1:19202381610:web:649a5f26dec8d010393053',
    messagingSenderId: '19202381610',
    projectId: 'tastefinder1',
    authDomain: 'tastefinder1.firebaseapp.com',
    storageBucket: 'tastefinder1.appspot.com',
    measurementId: 'G-Z8RR0MLZ75',
  );

}